CREATE DATABASE IF NOT EXISTS hr_management;
USE hr_management;

CREATE TABLE IF NOT EXISTS `service` (
  `N__SERVICE` int NOT NULL AUTO_INCREMENT,
  `ID_ENTREPRISE` int NOT NULL,
  `NOM_SERVICE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`N__SERVICE`),
  KEY `FK_SERVICE_APPARTENI_ENTREPRI` (`ID_ENTREPRISE`)
);

CREATE TABLE IF NOT EXISTS `employee` (
  `ID_EMP` int NOT NULL AUTO_INCREMENT,
  `N__SERVICE` int NOT NULL,
  `NOM_EMP` varchar(20) DEFAULT NULL,
  `PRENOM_EMP` varchar(20) DEFAULT NULL,
  `DATE_EMP` date DEFAULT NULL,
  `TEL_EMP` varchar(20) DEFAULT NULL,
  `EMAIL_EMP` varchar(30) DEFAULT NULL,
  `ADRESSE_EMP` varchar(50) DEFAULT NULL,
  `DATEEMBAUCH_EMP` date DEFAULT NULL,
  `NOMBRE_D_ENFANT` int DEFAULT NULL,
  `NOM_UTILISATEUR` varchar(20) DEFAULT NULL,
  `MOT_DE_PASSE` varchar(255) DEFAULT NULL,
  `ROLES` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_EMP`),
  KEY `FK_EMPLOYEE_TRAVAILLE_SERVICE` (`N__SERVICE`),
  CONSTRAINT `FK_EMPLOYEE_TRAVAILLE_SERVICE` FOREIGN KEY (`N__SERVICE`) REFERENCES `service` (`N__SERVICE`)
);

CREATE TABLE IF NOT EXISTS `absence` (
  `N__ABS` int NOT NULL AUTO_INCREMENT,
  `ID_EMP` int NOT NULL,
  `DUREE_ABS` int DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `MOTIF` text,
  `JUSTIF` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`N__ABS`),
  KEY `FK_ABSENCE_ASSOCIATI_EMPLOYEE` (`ID_EMP`),
  CONSTRAINT `FK_ABSENCE_ASSOCIATI_EMPLOYEE` FOREIGN KEY (`ID_EMP`) REFERENCES `employee` (`ID_EMP`)
);

CREATE TABLE IF NOT EXISTS `conge` (
  `N__CGE` int NOT NULL AUTO_INCREMENT,
  `ID_EMP` int NOT NULL,
  `DATE_DEBUT_CGE` date DEFAULT NULL,
  `DATE_FIN_CGE` date DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT 'PENDING',
  PRIMARY KEY (`N__CGE`),
  KEY `FK_CONGE_PRENDRE_EMPLOYEE` (`ID_EMP`),
  CONSTRAINT `FK_CONGE_PRENDRE_EMPLOYEE` FOREIGN KEY (`ID_EMP`) REFERENCES `employee` (`ID_EMP`)
);

CREATE TABLE IF NOT EXISTS `contrat` (
  `N__CONTRAT` int NOT NULL AUTO_INCREMENT,
  `ID_EMP` int NOT NULL,
  `TYPE_CONTRAT` varchar(40) DEFAULT NULL,
  `FONCTION` varchar(20) DEFAULT NULL,
  `QUALIFICATION` varchar(30) DEFAULT NULL,
  `CATEGORIE` varchar(40) DEFAULT NULL,
  `ECHLAN` varchar(10) DEFAULT NULL,
  `NBR_H_MOIS` int DEFAULT NULL,
  `NBR_H___JOURS` int DEFAULT NULL,
  `TYPE_DE_PAIE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`N__CONTRAT`),
  KEY `FK_CONTRAT_DETENIR_EMPLOYEE` (`ID_EMP`),
  CONSTRAINT `FK_CONTRAT_DETENIR_EMPLOYEE` FOREIGN KEY (`ID_EMP`) REFERENCES `employee` (`ID_EMP`)
);

CREATE TABLE IF NOT EXISTS `type_diplome` (
  `ID_TYPE_DPL` int NOT NULL AUTO_INCREMENT,
  `NOM_TYPE_DPL` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID_TYPE_DPL`)
);

CREATE TABLE IF NOT EXISTS `diplome` (
  `ID_DPL` int NOT NULL AUTO_INCREMENT,
  `ID_TYPE_DPL` int NOT NULL,
  `SPECIALITE_DPL` varchar(30) DEFAULT NULL,
  `MENTION_DPL` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID_DPL`),
  KEY `FK_DIPLOME_ASSOCIATI_TYPE_DIP` (`ID_TYPE_DPL`),
  CONSTRAINT `FK_DIPLOME_ASSOCIATI_TYPE_DIP` FOREIGN KEY (`ID_TYPE_DPL`) REFERENCES `type_diplome` (`ID_TYPE_DPL`)
);

CREATE TABLE IF NOT EXISTS `employee_diplome` (
  `ID_DPL` int NOT NULL,
  `ID_EMP` int NOT NULL,
  `DATE_OBTENTION_DIPLOME` date DEFAULT NULL,
  PRIMARY KEY (`ID_DPL`,`ID_EMP`),
  KEY `FK_EMP_DIP_EMPLOYEE` (`ID_EMP`),
  CONSTRAINT `FK_EMP_DIP_DIPLOME` FOREIGN KEY (`ID_DPL`) REFERENCES `diplome` (`ID_DPL`),
  CONSTRAINT `FK_EMP_DIP_EMPLOYEE` FOREIGN KEY (`ID_EMP`) REFERENCES `employee` (`ID_EMP`)
);

CREATE TABLE IF NOT EXISTS `salaire` (
  `ID_SLR` int NOT NULL AUTO_INCREMENT,
  `ID_EMP` int NOT NULL,
  `DATE_PAIEMENT` date DEFAULT NULL,
  `MONTANT` int DEFAULT NULL,
  PRIMARY KEY (`ID_SLR`),
  KEY `FK_SALAIRE_ASSOCIATI_EMPLOYEE` (`ID_EMP`),
  CONSTRAINT `FK_SALAIRE_ASSOCIATI_EMPLOYEE` FOREIGN KEY (`ID_EMP`) REFERENCES `employee` (`ID_EMP`)
); 